[versions]
archunit = "0.23.1"
jib = "3.2.1"
jib-ext-layer-filter = "0.3.0"
jsoup = "1.15.1"
newrelic-agent = "7.7.0"
newrelic-logback = "2.4.0"
spotless = "6.6.1"
spring-boot = "2.7.0"
versionsplg = "0.42.0"

[libraries]
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
flyway = { module = "org.flywaydb:flyway-core" }
jdbc-postgresql = { module = "org.postgresql:postgresql" }
jedis = { module = "redis.clients:jedis" }
jib-ext-layer-filter = { module = "com.google.cloud.tools:jib-layer-filter-extension-gradle", version.ref = "jib-ext-layer-filter" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
newrelic-agent = { module = "com.newrelic.agent.java:newrelic-agent", version.ref = "newrelic-agent" }
newrelic-logback = { module = "com.newrelic.logging:logback", version.ref = "newrelic-logback" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-session-data-redis = { module = "org.springframework.session:spring-session-data-redis" }

[plugins]
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
versionsplg = { id = "com.github.ben-manes.versions", version.ref = "versionsplg" }
