[versions]
archunit = "0.22.0"
jib = "3.1.4"
jsoup = "1.14.3"
newrelic-agent = "7.4.3"
newrelic-logback = "2.3.1"
spotless = "6.1.0"
spring-boot = "2.6.2"
versionsplg = "0.41.0"

[libraries]
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
newrelic-agent = { module = "com.newrelic.agent.java:newrelic-agent", version.ref = "newrelic-agent" }
newrelic-logback = { module = "com.newrelic.logging:logback", version.ref = "newrelic-logback" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

[plugins]
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
versionsplg = { id = "com.github.ben-manes.versions", version.ref = "versionsplg" }
