name: Deploy

on: workflow_dispatch

concurrency:
  group: deploy-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Configure JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: ci/deploy.sh
